<?php
/**
 * @file
 */

/**
 * Implements hook_init().
 */
function uom_events_init() {
  // Attempts to load the EventsAPI library, if available.
  $library = libraries_load('EventsAPI');
  foreach ($library['files']['php'] as $file) {
    require_once $library['library path'] . '/' . $file;
  }
}

/**
 * Implements hook_page_build().
 */
function uom_events_page_build(&$page) {
  $page['content']['uom_events'] = array(
    '#attached' => array(
      'css' => drupal_get_path('module', 'uom_events') . '/css/uom_events.css',
    ),
  );
}

/**
 * Implements hook_permission().
 */
function uom_events_permission() {
  return array(
    'administer uom events' => array(
      'title' => t('Administer UoM Events'),
      'description' => t('Configure the UoM events API.')
    ),
    'view uom events' => array(
      'title' => t('View UoM Events'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function uom_events_menu() {
  $items['admin/config/services/uom-events'] = array(
    'title' => t('UoM Events'),
    'description' => t('Configure the University of Melbourne event API.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uom_events_admin_form'),
    'access arguments' => array('administer uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.admin.inc',
  );

  $items['events'] = array(
    'title' => t('Events'),
    'page callback' => 'uom_events_page',
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  $items['events/devel'] = array(
    'title' => t('Events'),
    'page callback' => 'uom_events_page_devel',
    'access arguments' => array('access devel information'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'uom_events.pages.inc',
  );

  $items['events/%'] = array(
    'title' => t('Events'),
    'page callback' => 'uom_events_page',
    'page arguments' => array(1),
    'access arguments' => array('view uom events'),
    'type' => MENU_CALLBACK,
    'file' => 'uom_events.pages.inc',
  );

  $items['events/%/devel'] = array(
    'title' => t('Devel'),
    'page callback' => 'uom_events_page_devel',
    'page arguments' => array(1),
    'access arguments' => array('access devel info'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'uom_events.pages.inc',
  );

  $items['events/tag/%'] = array(
    'title' => t('Events'),
    'page callback' => 'uom_events_filter_page',
    'page arguments' => array('tag', 2),
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  $items['events/type/%'] = array(
    'title' => t('Events'),
    'page callback' => 'uom_events_filter_page',
    'page arguments' => array('type', 2),
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  $items['events/host/%'] = array(
    'title' => t('Events'),
    'page callback' => 'uom_events_filter_page',
    'page arguments' => array('host', 2),
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  $items['presenters'] = array(
    'title' => t('Presenters'),
    'page callback' => 'uom_events_presenters_page',
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  $items['presenters/%'] = array(
    'title' => t('Presenters'),
    'page callback' => 'uom_events_presenters_page',
    'page arguments' => array(1),
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  $items['recordings'] = array(
    'title' => t('Recordings'),
    'page callback' => 'uom_events_recordings_page',
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  $items['recordings/%'] = array(
    'title' => t('Recordings'),
    'page callback' => 'uom_events_recordings_page',
    'page arguments' => array(1),
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  $items['tags'] = array(
    'title' => t('Tags'),
    'page callback' => 'uom_events_tags_page',
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  $items['tags/%'] = array(
    'title' => t('Tags'),
    'page callback' => 'uom_events_tags_page',
    'page arguments' => array(1),
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  $items['hosts'] = array(
    'title' => t('Hosts'),
    'page callback' => 'uom_events_hosts_page',
    'access arguments' => array('view uom events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uom_events.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_libraries_info().
 */
function uom_events_libraries_info() {
  $libraries['EventsAPI'] = array(
    'name' => 'UoM Events API',
    'vendor url' => 'http://events.unimelb.edu.au/',
    'download url' => 'https://github.com/cafuego/uom_events_api',
    'path' => 'EventsAPI',
    'version arguments' => array(
      'file' => 'EventsAPI.php',
      // Best practice: Document the actual version strings for later reference.
      //  const EVENTS_API = 'api/v1';
      'pattern' => '/const EVENTS_API = \'api\/v(\d+)\'/',
      'lines' => 25,
    ),
    'files' => array(
      'php' => array('library' => 'EventsAPI.php'),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_theme().
 */
function uom_events_theme($existing, $type, $theme, $path) {
  return array(
    'uom_event_list' => array(
      'variables' => array('events' => NULL),
      'base hook' => 'uom_event_list',
      'template' => 'uom-event-list',
      'path' => drupal_get_path('module', 'uom_events') . '/templates',
    ),
    'uom_event' => array(
      'variables' => array('event' => NULL),
      'base hook' => 'uom_event',
      'template' => 'uom-event',
      'path' => drupal_get_path('module', 'uom_events') . '/templates',
    ),
    'uom_event_location' => array(
      'variables' => array('location' => NULL),
      'file' => 'uom_events.theme.inc',
    ),
    'uom_event_information' => array(
      'variables' => array('information' => NULL),
      'file' => 'uom_events.theme.inc',
    ),
    'uom_event_booking' => array(
      'variables' => array('booking' => NULL),
      'file' => 'uom_events.theme.inc',
    ),
    'uom_event_presenter_list' => array(
      'variables' => array('presenters' => NULL),
      'base hook' => 'uom_event_presenter_list',
      'template' => 'uom-event-presenter-list',
      'path' => drupal_get_path('module', 'uom_events') . '/templates',
    ),
    'uom_event_presenter' => array(
      'variables' => array('presenter' => NULL),
      'base hook' => 'uom_event_presenter',
      'template' => 'uom-event-presenter',
      'path' => drupal_get_path('module', 'uom_events') . '/templates',
    ),
  );
}

/**
 * Helper that fetches data via drupal_http_request() and optionally
 * caches the result.
 *
 * @param $url
 *   A valid HTTP URL.
 * @param $options
 *   An array of additional options to pass to drupal_http_request().
 *
 * @return
 *   A HTTP response object.
 */
function uom_events_fetcher($url, $options) {
  $period = variable_get('cache_lifetime', 0);

  $hash = md5($url);
  if ($period  && $cache = cache_get('uom_events:' . $hash)) {
    return $cache->data;
  }
  else {
    $response = drupal_http_request($url, $options);
    if ($response->code != 200) {
      drupal_set_message(t('Unable to fetch event data from API. Error @code: @status', array('@code' => $response->code, '@status' => $response->status_message)));
    }
    elseif ($period) {
      // Cache it for at least 15 minutes, but really should have tweakable expiry.
      cache_set('uom_events:' . $hash, $response, 'cache', time() + $period);
    }
  }
  return $response;
}

/**
 * Helper that parses a drupal_http_request() and does some error checking.
 *
 * @param $response.
 *   A HTTP response object.
 *
 * @return
 *   An object or array of objects on success, FALSE on failure.
 */
function uom_events_parser($response) {
  if ($response->code == 200) {
    return @json_decode($response->data);
  }
  drupal_set_message(t('Unable to fetch event data from API. Error @code: @status', array('@code' => $response->code, '@status' => $response->status_message)));
  return FALSE;
}

/**
 * Wrapper that returns an initialised API class.
 */
function uom_events_api() {
  $api = new EventsAPI(variable_get('uom_events_token', ''));
  $api->setCallback('uom_events_fetcher');
  $api->setParser('uom_events_parser');

  return $api;
}

/**
 * Preprocess an event object for the template file.
 */
function uom_events_preprocess_uom_event(&$variables) {
  $event = $variables['event'];
  unset($variables['event']);

  $timestamp_start = strtotime($event->start_time);
  $timestamp_end   = strtotime($event->end_time);

  $variables['id']                = $event->id;
  $variables['title']             = check_plain($event->title);
  $variables['link']              = url('events/'. $event->id);
  $variables['description']       = (empty($event->description)) ? '' : check_plain($event->description);
  $variables['description_html']  = (empty($event->description_html)) ? '' : filter_xss($event->description_html);
  $variables['description_text']  = (empty($event->description_text)) ? '' : check_plain($event->description_text);
  $variables['timestamp_start']   = $timestamp_start;
  $variables['timestamp_end']     = $timestamp_end;
  $variables['datestamp_start']   = $event->start_time;
  $variables['datestamp_end']     = $event->end_time;
  $variables['date']              = format_date($timestamp_start, 'long');
  $variables['date_start']        = (empty($event->start_time)) ? '' : format_date($timestamp_start, 'custom', 'l, F j, Y');
  $variables['date_end']          = (empty($event->end_time)) ? '' : format_date($timestamp_end, 'custom', 'l, F j, Y');
  $variables['time_start']        = (empty($event->start_time)) ? '' : format_date($timestamp_start, 'custom', 'G:i');
  $variables['time_end']          = (empty($event->end_time)) ? '' : format_date($timestamp_end, 'custom', 'G:i');
  $variables['speaker']           = (empty($event->speaker)) ? '' : check_plain($event->speaker);
  $variables['location']          = (empty($event->location)) ? '' : theme('uom_event_location', array('location' => $event->location));
  $variables['information']       = (empty($event->information)) ? '' : theme('uom_event_information', array('information' => $event->information));
  $variables['booking']           = (empty($event->booking)) ? '' : theme('uom_event_booking', array('booking' => $event->booking));
  $variables['host']              = (empty($event->host)) ? '' : check_plain($event->host);
  $variables['image']             = (empty($event->img_url)) ? '' : $event->img_url;
  $variables['type']              = (empty($event->event_type)) ? '' : $event->event_type;
  $variables['bookings_required'] = (empty($event->bookings_required)) ? '' : $event->bookings_required;
  $variables['sold_out']          = (empty($event->sold_out)) ? '' : $event->sold_out;
  $variables['cancelled']         = (empty($event->cancelled)) ? '' : $event->cancelled;
  $variables['original']          = url($event->link);
}

/**
 * Preprocess an event list array for the template file.
 */
function uom_events_preprocess_uom_event_list(&$variables) {
  $events = $variables['events'];
  $variables['events'] = array();;

  // Process the list of event objects into an array of template variables.
  // Wednesday, May 22, 2013 - 18:00–19:00
  foreach ($events as $event) {

    $timestamp_start = strtotime($event->start_time);
    $timestamp_end   = strtotime($event->end_time);

    $variables['events'][$event->id] = array(
      'id'               => $event->id,
      'title'            => check_plain($event->title),
      'link'             => url('events/'. $event->id),
      'description'      => (empty($event->description)) ? '' : check_plain($event->description),
      'description_html' => (empty($event->description_html)) ? '' : filter_xss($event->description_html),
      'description_text' => (empty($event->description_text)) ? '' : check_plain($event->description_text),
      'timestamp_start'  => $timestamp_start,
      'timestamp_end'    => $timestamp_end,
      'datestamp_start'  => $event->start_time,
      'datestamp_end'    => $event->end_time,
      'date'             => format_date($timestamp_start, 'long'),
      'date_start'       => (empty($event->start_time)) ? '' : format_date($timestamp_start, 'custom', 'l, F j, Y'),
      'date_end'         => (empty($event->end_time)) ? '' : format_date($timestamp_end, 'custom', 'l, F j, Y'),
      'time_start'       => (empty($event->start_time)) ? '' : format_date($timestamp_start, 'custom', 'G:i'),
      'time_end'         => (empty($event->end_time)) ? '' : format_date($timestamp_end, 'custom', 'G:i'),
      'speaker'          => (empty($event->speaker)) ? '' : check_plain($event->speaker),
      'location'         => (empty($event->location)) ? '' : theme('uom_event_location', array('location' => $event->location)),
      'information'      => (empty($event->information)) ? '' : theme('uom_event_information', array('information' => $event->information)),
      'booking'          => (empty($event->booking)) ? '' : theme('uom_event_booking', array('booking' => $event->booking)),
      'host'             => (empty($event->host)) ? '' : check_plain($event->host),
      'image'            => (empty($event->img_url)) ? '' : $event->img_url,
      'type'             => (empty($event->event_type)) ? '' : $event->event_type,
      'has_livestream'   => (empty($event->has_livestream)) ? '' : $event->has_livestream,
      'sold_out'         => (empty($event->sold_out)) ? '' : $event->sold_out,
      'cancelled'        => (empty($event->cancelled)) ? '' : $event->cancelled,
      'original'         => url($event->link),
    );
  }
}

/**
 * Preprocess a presenter object for the template file.
 */
function uom_events_preprocess_uom_event_presenter(&$variables) {
  $presenter = $variables['presenter'];
  unset($variables['presenter']);

  $variables['id']                          = $presenter->id;
  $variables['link']                        = url('presenters/'. $presenter->id);
  $variables['title']                       = check_plain($presenter->title);
  $variables['first_name']                  = check_plain($presenter->first_name);
  $variables['last_name']                   = check_plain($presenter->last_name);
  $variables['post_nominal']                = check_plain($presenter->post_nominal);
  $variables['full_name']                   = t('@title @first @last @post', array('@title' => $presenter->title, '@first' => $presenter->first_name, '@last' => $presenter->last_name, '@post' => $presenter->post_nominal));
  $variables['organisation']                = check_plain($presenter->organisation);
  $variables['position_title']              = check_plain($presenter->position_title);
  $variables['biography']                   = check_plain($presenter->biography);
  $variables['biography_html']              = filter_xss($presenter->biography_html);
  $variables['biography_text']              = check_plain($presenter->biography_text);
  $variables['country']                     = check_plain($presenter->country);
  $variables['content_approved_by_speaker'] = $presenter->content_approved_by_speaker;
  $variables['find_an_expert_url']          = url($presenter->find_an_expert_url);
  $variables['photo_url']                   = url($presenter->photo_url);
  $variables['photo']                       = theme('image', array('path' => $presenter->photo_url));
  $variables['original']                    = $presenter->link;
}

/**
 * Preprocess a presenter list array for the template file.
 */
function uom_events_preprocess_uom_event_presenter_list(&$variables) {
  $presenters = $variables['presenters'];
  $variables['presenters'] = array();

  foreach ($presenters as $presenter) {
    $variables['presenters'][$presenter->id] = array(
      'id'             => $presenter->id,
      'link'           => url('presenters/' . $presenter->id),
      'title'          => check_plain($presenter->title),
      'first_name'     => check_plain($presenter->first_name),
      'last_name'      => check_plain($presenter->last_name),
      'post_nominal'   => check_plain($presenter->post_nominal),
      'full_name'      => t('@title @first @last @post', array('@title' => $presenter->title, '@first' => $presenter->first_name, '@last' => $presenter->last_name, '@post' => $presenter->post_nominal)),
      'organisation'   => check_plain($presenter->organisation),
      'position_title' => check_plain($presenter->position_title),
      'photo_url'      => url($presenter->photo_url),
      'photo'          => theme('image', array('path' => $presenter->photo_url)),
      'original'       => $presenter->link,
    );
  }
}
